package com.example.hotelrooms.navigation

const val Route_register = "registerScreen"
const val Route_login = "loginScreen"
const val Route_home = "homeScreen"
const val Route_book = "bookScreen"
const val Route_update = "updateClientScreen"
const val Route_view = "viewClientScreen"
const val Route_Entry = "EntryScreen"
const val Route_view_client = "ViewClient"
const val Route_add_rooms = "addRooms"
const val Route_view_rooms = "viewRooms"
const val Route_update_rooms = "updateRoom"
const val Route_View_Rooms_User = "viewRoomsUser"
const val Route_Thanks = "thankYouClient"